# Site settings
title: "Gilvir's Portfolio"
description: > 
  Hello! I'm Gilvir, an NYC-based programmer and student. Thank you for checking out my portfolio and blog!

author: Gilvir Gill
email: personal@gilvirgill.com
github_username: gillgamesh

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gilvirgill.com" # the base hostname & protocol for your site

google_analytics_id: UA-1111111111-1
disqus_id:

collections:
    projects:
        output: true
# Build settings
include: [_pages, _projects]
markdown: kramdown
permalink: /:year/:month/:title.html
excerpt_separator: <!--more-->

sass:
    style: compressed



exclude: [vendor]

